# Generated by Django 4.2.16 on 2024-10-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='body_type',
            field=models.CharField(choices=[('Klepsydra', 'Klepsydra'), ('Gruszka', 'Gruszka'), ('Jabłko', 'Jabłko'), ('Prostokąt', 'Prostokąt'), ('Trójkąt', 'Trójkąt')], default='Jabłko', max_length=10),
        ),
    ]
