# Generated by Django 4.2.16 on 2024-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0005_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inne')], default=1),
        ),
    ]
