# Generated by Django 4.2.16 on 2024-10-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0006_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
